services:
  asmbb:
    image: dhclly/asmbb-v3.0.0-amd64-cn:latest
    container_name: asmbb
    restart: unless-stopped
    ports:
    - 20414:20414
    environment:
    - TZ=${TZ:-America/Los_Angeles}
    - PUID=${PUID:-1000}
    - PGID=${PGID:-1000}
    volumes:
    - ./config:/config
    - ./data:/data
    healthcheck:
      test:
      - CMD-SHELL
      - nc -z 127.0.0.1 20414 || exit 1
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
networks:
  default:
    name: asmbb_net
