services:
  firecamp:
    image: cloudstax/firecamp-kafka:latest
    container_name: firecamp
    restart: unless-stopped
    ports:
    - 20443:20443
    environment:
    - TZ=${TZ:-America/Los_Angeles}
    - PUID=${PUID:-1000}
    - PGID=${PGID:-1000}
    volumes:
    - ./config:/config
    - ./data:/data
    healthcheck:
      test:
      - CMD-SHELL
      - nc -z 127.0.0.1 20443 || exit 1
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
networks:
  default:
    name: firecamp_net
