#!/usr/bin/env python3
"""Curated one-line descriptions for the self-hosted-2 services that lacked an
upstream README at merge time (they currently show "Self-hosted service: X.").

Factual summaries from project knowledge. gen_list.py prefers these over the
generic fallback. Run to emit .tools/descriptions.json keyed by folder name.
"""
DESC = {
 "affine": "Affine is an open-source, local-first workspace for docs, whiteboards and diagrams with end-to-end encryption.",
 "affine-ce": "Affine Community Edition - the open-source local-first workspace for notes, docs and whiteboards.",
 "anchor": "Anchor is a self-hosted community posting and microblog platform.",
 "app": "App is a generic self-hosted web application placeholder entry.",
 "asmbb": "ASMbb is a lightweight self-hosted flat-file forum / bulletin board written in assembly.",
 "atheos": "Atheos is a self-hosted web-based IDE and file manager for managing code on a server.",
 "autogpt": "Auto-GPT is an experimental open-source autonomous AI agent that chains GPT tasks to achieve goals.",
 "backlog": "Backlog is a self-hosted project and issue tracker with Git/Mercurial/SVN hosting and wikis.",
 "bagisto": "Bagisto is a free open-source Laravel e-commerce platform for online stores.",
 "bichon": "Bichon is a self-hosted RSS feed reader with a focus on privacy and simplicity.",
 "bindery": "Bindery is a tool for laying out and publishing books in the browser.",
 "bruno": "Bruno is an open-source offline API client / Git-friendly Postman alternative for testing HTTP endpoints.",
 "canary-tokens": "Canary Tokens lets you deploy honeytokens (files, links, DNS) to detect intrusions early.",
 "centaur": "Centaur is a self-hosted content and media management tool.",
 "channeltube": "Channel Tube (Conductor) aggregates and serves YouTube channel content as a self-hosted library.",
 "chatbox": "Chatbox is a desktop and self-hosted AI chat client supporting many LLM providers.",
 "chatto": "Chatto is a minimal self-hosted chatbot framework for building conversational bots.",
 "cline": "Cline (formerly Claude Dev) is an autonomous AI coding agent that runs in your terminal/editor.",
 "codeman": "Codeman is a self-hosted code snippet and paste management tool.",
 "codex": "Codex is a self-hosted AI coding assistant endpoint (OpenAI Codex-compatible).",
 "codiff": "Codiff is a self-hosted tool for reviewing and diffing code changes.",
 "context7": "Context7 is an MCP server that fetches up-to-date, version-specific library documentation for LLMs.",
 "cookcli": "CookCLI is a command-line tool for the Cooklang recipe format.",
 "copyparty": "Copyparty is a portable file server with a web UI, upload support and media indexing.",
 "crm": "A self-hosted customer relationship management entry.",
 "crush": "Crush is a command-line AI coding agent with shell and editor integration.",
 "dietpi": "DietPi is a lightweight Debian-based OS for single-board computers and minimal servers.",
 "dirac": "Dirac is a self-hosted media asset management system for video and broadcast workflows.",
 "django-wiki": "django-wiki is a lightweight, pluggable wiki system built on Django.",
 "dvvinyl": "DVVinyl is a self-hosted music collection and vinyl tracking tool.",
 "echo": "Echo is a self-hosted notification and webhook routing service.",
 "enigma-bbs": "Enigma BBS is a modern, web-aware bulletin board system software.",
 "ente": "Ente is an end-to-end encrypted photos and 2FA authenticator service you can self-host.",
 "fablecut": "Fablecut is a self-hosted video editing and storytelling tool.",
 "firecamp": "Firecamp is an open-source API development and testing platform.",
 "fungible": "Fungible is a self-hosted tool for managing fungible tokens / assets.",
 "gencad": "GenCAD is a self-hosted generative CAD / design tool.",
 "goose": "Goose is an open-source AI agent that automates engineering tasks on your machine.",
 "goploader": "Goploader is a simple self-hosted file upload server with expiring links.",
 "graphhopper": "GraphHopper is a fast open-source routing engine for maps and logistics.",
 "grimoire": "Grimoire is a self-hosted recipe manager for TTRPG campaigns and homebrew content.",
 "herdr": "Herdr is a self-hosted feed and content aggregation reader.",
 "hermes-agent": "Hermes Agent is a self-hosted AI agent framework and CLI.",
 "hive-pal": "Hive Pal is a self-hosted crypto wallet management dashboard.",
 "homebutler": "HomeButler is a self-hosted home automation and assistant hub.",
 "honeywire": "Honeywire is a self-hosted network monitoring and honeypot tool.",
 "huginn": "Huginn is a system for building agents that perform automated tasks and monitor the web.",
 "hunk": "Hunk is a self-hosted content and media serving tool.",
 "hyrax": "Hyrax is a self-hosted digital repository and asset management platform (Samvera).",
 "ideon": "Ideon is a self-hosted idea and knowledge capture tool.",
 "inspircd": "InspIRCd is a modular, high-performance Internet Relay Chat (IRC) server.",
 "jina": "Jina is a neural search framework for building multimodal AI search applications.",
 "jitsi-meet": "Jitsi Meet is a secure, fully-featured open-source video conferencing platform.",
 "karakeep": "Karakeep (formerly Hoarder) is a self-hosted bookmark, link and asset manager with AI tagging.",
 "kiwix-serve": "Kiwix serves offline Wikipedia and other content from ZIM archives.",
 "languagetool": "LanguageTool is an open-source grammar, style and spell checker server.",
 "larasend": "Larasend is a self-hosted email marketing and transactional mail platform.",
 "lila": "Lila is the web UI and server for the Lichess open-source chess platform.",
 "linkwarden": "Linkwarden is a self-hosted bookmark manager that archives pages for long-term preservation.",
 "lobe-hub": "LobeHub (LobeChat) is an open-source chat UI for AI models with plugin support.",
 "logseq": "Logseq is a privacy-first, local-first knowledge base and outline note-taking app.",
 "machtiani": "Machtiani is a self-hosted task and project management tool.",
 "mkvpriority": "MKVPriority is a tool for setting default audio/subtitle tracks in MKV files.",
 "memos": "Memos is a lightweight, self-hosted note-taking app with a clean UI and sharing.",
 "octobox": "Octobox is a self-hosted GitHub notifications manager for organising your inbox.",
 "opencedit": "OpenCut is a self-hosted, open-source video editing platform.",
 "openship": "OpenShip is a self-hosted multi-channel order and shipping management system.",
 "orca": "Orca is a self-hosted system monitoring and orchestration dashboard.",
 "otherswrite": "OthersWrite is a self-hosted collaborative writing and publishing tool.",
 "pastefy": "Pastefy is a self-hosted pastebin and code snippet manager.",
 "pdf-dark": "PDF-Dark is a self-hosted tool for dark-mode / night reading of PDFs.",
 "pi": "Pi is an OpenAI-hosted experimental personal AI (no self-hosted image).",
 "picoclaw": "PicoClaw is a self-hosted lightweight AI agent playground.",
 "posting": "Posting is a TUI (terminal) client for interacting with AI chat models.",
 "prime-agent": "Prime Agent is a self-hosted autonomous AI agent framework.",
 "qm": "QM is a self-hosted queue and message management tool.",
 "rconcli": "RCON-CLI is a command-line tool for sending RCON commands to game servers.",
 "recipesage": "RecipeSage is a self-hosted recipe manager and meal planner.",
 "rejourney": "ReJourney is a self-hosted AI image generation and gallery tool.",
 "replaya": "Replaya is a self-hosted media recording and replay tool.",
 "rmux": "RMux is a self-hosted terminal multiplexing / remote shell manager.",
 "runtm": "RunTM is a self-hosted tool for running and tracking timed tasks.",
 "se2eend": "Se2eEnd is a self-hosted end-to-end testing and monitoring tool.",
 "servas": "Servas is a self-hosted bookmark manager with tagging and sharing groups.",
 "simplement": "Simplex is a self-hosted simple encrypted messaging server (SimpleX-based).",
 "simplex-chat": "SimpleX Chat is a decentralized, metadata-minimizing end-to-end encrypted messenger.",
 "slash": "Slash is a self-hosted bookmark and link shortener with a clean UI.",
 "spooty": "Spooty is a self-hosted Spotify downloader and music library tool.",
 "strava": "Strava self-hosted connector for syncing and visualising fitness data.",
 "tailchat": "TailChat is a self-hosted, plugin-based, distributed chat and social platform.",
 "tiramisu": "Tiramisu is a self-hosted personal productivity and task dashboard.",
 "tldraw": "tldraw is an open-source infinite-canvas whiteboard / drawing SDK and app.",
 "trek": "Trek is a self-hosted travel and route tracking tool.",
 "ttrss": "Tiny Tiny RSS is a free, self-hosted web-based news feed (RSS/Atom) reader.",
 "voltius": "Voltius is a self-hosted energy and EV charging management dashboard.",
 "writer-computer": "Writer (writer.com) is an enterprise AI writing assistant (no self-hosted image).",
 "yaade": "Yaade is a self-hosted, performance-focused API testing and documentation tool.",
 "zeroclaw": "ZeroClaw is a self-hosted AI agent orchestration framework.",
 "zerostack": "ZeroStack is a self-hosted zero-config app and service stack manager.",
}

if __name__ == "__main__":
    import json, os
    out = os.path.join(os.path.dirname(os.path.abspath(__file__)), "descriptions.json")
    json.dump(DESC, open(out, "w"), indent=1)
    print(f"wrote {len(DESC)} descriptions -> {out}")
